export const ROUTE_NAMES = {
  HOME: "home",
  ARTICLES: "articles",
  ARTICLE_DETAIL: "article-detail",
  AUTH: "auth",
  NOTIFICATIONS: "notifications",
  AI_CHAT: "ai-chat",
  USER_PROFILE: "user-profile",
  ADMIN_HOME: "admin-home",
  ADMIN_DASHBOARD: "admin-dashboard",
  ADMIN_POSTS: "admin-posts",
  ADMIN_POST_CREATE: "admin-post-create",
  ADMIN_POST_EDIT: "admin-post-edit",
  ADMIN_CATEGORIES: "admin-categories",
  ADMIN_TAGS: "admin-tags",
  ADMIN_USERS: "admin-users",
  ADMIN_DECORATIONS: "admin-decorations",
  ADMIN_UV: "admin-uv",
};
